/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "OwnableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUpgradeable__factory>;
    getContractFactory(
      name: "PausableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PausableUpgradeable__factory>;
    getContractFactory(
      name: "ERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Upgradeable__factory>;
    getContractFactory(
      name: "ERC20PermitUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20PermitUpgradeable__factory>;
    getContractFactory(
      name: "IERC20PermitUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20PermitUpgradeable__factory>;
    getContractFactory(
      name: "IERC20MetadataUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20MetadataUpgradeable__factory>;
    getContractFactory(
      name: "IERC20Upgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Upgradeable__factory>;
    getContractFactory(
      name: "ClaimableUpgradeable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ClaimableUpgradeable__factory>;
    getContractFactory(
      name: "Lif2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lif2__factory>;
    getContractFactory(
      name: "Lif2V2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lif2V2__factory>;
    getContractFactory(
      name: "OldLifTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OldLifTest__factory>;
    getContractFactory(
      name: "Lif2Test",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lif2Test__factory>;
    getContractFactory(
      name: "Lif2TestV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lif2TestV2__factory>;
    getContractFactory(
      name: "Lif2UpgradeabilityTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lif2UpgradeabilityTest__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
