/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  StoppableUpgradeable,
  StoppableUpgradeableInterface,
} from "../StoppableUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Stopped",
    type: "event",
  },
  {
    inputs: [],
    name: "stopped",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class StoppableUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): StoppableUpgradeableInterface {
    return new utils.Interface(_abi) as StoppableUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StoppableUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as StoppableUpgradeable;
  }
}
